# -*- coding: utf-8 -*-
"""pop_w_exposure_gee_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/105zZnALSVbbXPaiBMzhzfnuDGoydLZGK

pop_w_exposure.py
=====================================
Refactored GEE workflow — Pop. Exposure + Pop-Weighted Hazard Intensity

For each subnational admin area and each hazard layer, this script computes:
  1. Exposed population (using absolute / global-mean / country-mean thresholds)
  2. Pop-weighted average hazard intensity (with two weighting strategies)
  3. Data-coverage quality metrics

─────────────────────────────────────────────────────────────────────────────
DESIGN DECISIONS (read alongside the code)
─────────────────────────────────────────────────────────────────────────────

A. RESTRUCTURED HAZARD CONFIGURATION

   Each *unique physical layer* is defined once, with a list of the
   threshold variants it needs. Exposed-population is computed once per
   threshold variant. Weighted average is computed once per layer
   (it doesn't depend on thresholds), with two possible strategies.

B. reduceRegions INSTEAD OF reduceRegion-IN-A-LOOP
   The original script looped: for each admin → for each hazard → reduceRegion.
   With N admins × M hazards, that's N×M separate server-side calls, each
   triggering a full pixel scan of the admin region.

   reduceRegions (plural) processes ALL admin features in a single server-side
   operation per hazard layer. This changes the complexity from O(N×M) calls
   to O(M) calls — a dramatic reduction in round-trips and GEE overhead.

   Trade-off: reduceRegions loads the entire admin FeatureCollection into
   memory at once. For very large FCs (>10k features), this can hit GEE
   memory limits. For subnational admin1/admin2 boundaries of a single
   country, this is well within limits.

C. MULTI-BAND STACKING
   For each hazard, instead of running several separate reductions (one for
   exposed pop, one for H×P, one for P, etc.), we stack all needed quantities
   as bands of a single ee.Image and reduce once with ee.Reducer.sum().
   GEE evaluates all bands in a single pixel traversal, which is substantially
   faster than separate reduceRegions calls.

D. TWO WEIGHTING STRATEGIES FOR THE POPULATION-WEIGHTED AVERAGE

   The population-weighted average of hazard H over admin region R is:

       H̄_R = Σ(H_i × P_i) / Σ(P_i)

   The question is: over which pixels i do we sum?

   Strategy A — "Total-population weights" (appropriate when nodata = no hazard = 0):
     Denominator = Σ P_i  over ALL pixels with population data in R.

     Key insight: the denominator includes population in nodata-hazard areas.
     This is correct when nodata genuinely means zero intensity (e.g.
     flood depth, wind speed): those people experience zero hazard, pulling
     the area-wide average down legitimately.

   Strategy B — "Intersection weights" (appropriate when nodata = missing data):
     Denominator = Σ P_i  only where BOTH H and P have data.

     Key insight: avoids the "dilution" effect. If a drought index (SPI/SPEI)
     has coverage over only 10% of the admin area, Strategy A would divide by
     the full population, shrinking the average towards zero — misleading,
     because the missing 90% isn't "no drought", it's "no data". Strategy B
     divides only by the population in the data-covered area, giving a
     representative average of observed conditions.

   Key insight on both strategies: Numerator = Σ (H_i × P_i) is the same in both
   cases because GEE masks propagate through multiply.

   The script computes numerator and BOTH denominators in a single pass,
   then in post-processing selects the recommended strategy per hazard
   (controlled by the `nodata_means_zero` flag) and also outputs the
   alternative for transparency.

E. DATA-COVERAGE QC METRIC
   For each admin × hazard combination:
     pop_data_coverage = p_both / p_total

   This is a population-weighted coverage fraction: what share of the admin's
   population lives in pixels where the hazard layer has actual data.
   A value of 0.10 means only 10% of the population is "covered" by the
   hazard data — a strong signal that the weighted average should be interpreted
   with caution, using Strategy A/B and `nodata_means_zero` flag accordingly.

F. EXPORT STRUCTURE
   One GEE export task per hazard layer (not per admin as before). Each CSV
   contains one row per admin feature with columns for all the component sums.
   Final derived metrics (weighted averages, coverage ratios) are computed in
   the pandas post-processing step, avoiding the need to do division inside
   GEE (which would require mapping over features and adds complexity).
─────────────────────────────────────────────────────────────────────────────
"""

from google.colab import drive
drive.mount('/content/drive')

import ee
import pandas as pd
import os
import glob
import json
import time
from datetime import datetime, timezone

# ── Initialize ───────────────────────────────────────────────────────────
ee.Authenticate()
ee.Initialize(project='unicef-ccri')

# =========================================================================
# 1. CONFIGURATION
# =========================================================================

# --- Admin boundaries ---
id_name = 'adm1_pcode'      # column name in output CSVs
gee_id_field = 'adm1_pcode' # property name in the GEE FeatureCollection asset
parent_id = ''
admin_asset_id = "projects/unicef-ccri/assets/misc_boundaries/GRD_adm1"
admin_fc = ee.FeatureCollection(admin_asset_id)

# Filter for conflicted admin parents (if provided)
# E.g. Lebanon adm3 has conflicted parent pcodes
admin_fc = admin_fc.filter(
    ee.Filter.neq(parent_id, 'Conflict')
) if parent_id else admin_fc

country_geom = admin_fc.geometry()
suffix = 'grd_adm1'
output_folder = f'{suffix}_exposure_wavg'

# --- Population ---
pop_asset_id = "projects/unicef-ccri/assets/population/worldpop_T_2025_CN_100m"
org_totalpop = ee.ImageCollection(pop_asset_id)
totalpop = org_totalpop.mosaic()
pop_scale = org_totalpop.first().projection().nominalScale()

# --- Reference scale (used for mean-threshold computation) ---------
reference_image = ee.Image(
    "projects/unicef-ccri/assets/heatwaves/heatwave_frequency_2014_2023_avg"
)
target_scale = reference_image.projection().nominalScale()

# --- Global geometry (for global-mean thresholds) ---
global_geo_id = "projects/unicef-ccri/assets/misc_boundaries/adm0_simple"
simple_fc = ee.FeatureCollection(global_geo_id)
global_geom = simple_fc.geometry()

# =========================================================================
# 2. HAZARD LAYER DEFINITIONS
# =========================================================================
# Each entry is a unique physical hazard layer. Fields:
#
#   asset_id          GEE asset path
#   name              Human-readable base name (used in output filenames)
#   is_collection     True → load as ee.ImageCollection(...).mosaic()
#   nodata_means_zero True → nodata pixels represent zero hazard intensity
#                     (flood depth, wind speed, landslide susceptibility, etc.)
#                     False → nodata means missing / no observation available
#                     (drought indices, temperature metrics, etc.)
#   comparison        "gt" or "lt" — direction of threshold for exposed pop
#   pre_mask_lte      (optional) pre-mask layer to values ≤ this number
#   thresholds        list of dicts, each with:
#       type   "absolute" | "global_mean" | "country_mean"
#       value  numeric (only for "absolute")
#       label  short suffix for the exposed-pop column in the output

hazard_layers = [
    {
        "asset_id": "projects/unicef-ccri/assets/hazards/river_flood_r100",
        "name": "river_flood_100yr_jrc_2024",
        "is_collection": True,
        "nodata_means_zero": True,
        "comparison": "gt",
        "thresholds": [
            {"type": "absolute", "value": 0.01, "label": "abs"},
        ],
    },
    {
        "asset_id": "projects/unicef-ccri/assets/hazards/coastal_flood_r100",
        "name": "coastal_flood_100yr_jrc_2024",
        "is_collection": True,
        "nodata_means_zero": True,
        "comparison": "gt",
        "thresholds": [
            {"type": "absolute", "value": 0, "label": "abs"},
        ],
    },
    {
        "asset_id": "projects/unicef-ccri/assets/hazards/storm_giri_rp100",
        "name": "tropical_storm_100yr_giri_2024",
        "is_collection": True,
        "nodata_means_zero": True,
        "comparison": "gt",
        "thresholds": [
            {"type": "absolute", "value": 17.5, "label": "abs"},
        ],
    },
    {
        "asset_id": "projects/unicef-ccri/assets/hazards/ASI_return_level_100yr",
        "name": "agricultural_drought_fao_1984-2023",
        "is_collection": False,
        "nodata_means_zero": False,
        "comparison": "gt",
        "pre_mask_lte": 100,
        "thresholds": [
            {"type": "absolute", "value": 30, "label": "abs"},
        ],
    },
    {
        "asset_id": "projects/unicef-ccri/assets/hazards/drought_spi_copernicus_1940_2024",
        "name": "drought_spi_copernicus_1940-2024",
        "is_collection": False,
        "nodata_means_zero": False,
        "comparison": "lt",
        "thresholds": [
            {"type": "absolute", "value": -1.5, "label": "abs"},
        ],
    },
    {
        "asset_id": "projects/unicef-ccri/assets/hazards/drought_spei_copernicus_1940_2024",
        "name": "drought_spei_copernicus_1940-2024",
        "is_collection": False,
        "nodata_means_zero": False,
        "comparison": "lt",
        "thresholds": [
            {"type": "absolute", "value": -1.5, "label": "abs"},
        ],
    },
    {
        "asset_id": "projects/unicef-ccri/assets/hazards/heatwave_frequency_return_level_100yr",
        "name": "heatwave_frequency_ecmwf_2014-2024",
        "is_collection": False,
        "nodata_means_zero": False,
        "comparison": "gt",
        "thresholds": [
            {"type": "global_mean", "label": "gmean"},
            {"type": "country_mean", "label": "cmean"},
        ],
    },
    {
        "asset_id": "projects/unicef-ccri/assets/hazards/heatwave_duration_return_level_100yr",
        "name": "heatwave_duration_ecmwf_2014-2024",
        "is_collection": False,
        "nodata_means_zero": False,
        "comparison": "gt",
        "thresholds": [
            {"type": "global_mean", "label": "gmean"},
            {"type": "country_mean", "label": "cmean"},
        ],
    },
    {
        "asset_id": "projects/unicef-ccri/assets/hazards/heatwave_severity_return_level_100yr",
        "name": "heatwave_severity_ecmwf_2014-2024",
        "is_collection": False,
        "nodata_means_zero": False,
        "comparison": "gt",
        "thresholds": [
            {"type": "global_mean", "label": "gmean"},
            {"type": "country_mean", "label": "cmean"},
        ],
    },
    {
        "asset_id": "projects/unicef-ccri/assets/hazards/high_temp_degree_days_return_level_100yr",
        "name": "extreme_heat_ecmwf_2014-2024",
        "is_collection": False,
        "nodata_means_zero": False,
        "comparison": "gt",
        "thresholds": [
            {"type": "absolute", "value": 35, "label": "abs"},
        ],
    },
    {
        "asset_id": "projects/unicef-ccri/assets/hazards/Pv_average_2013_2022",
        "name": "vectorborne_malariapv_2012-2022",
        "is_collection": False,
        "nodata_means_zero": True,
        "comparison": "gt",
        "thresholds": [
            {"type": "absolute", "value": 0.001, "label": "abs"},
        ],
    },
    {
        "asset_id": "projects/unicef-ccri/assets/hazards/Pf_average_2013_2022",
        "name": "vectorborne_malariapf_2012-2022",
        "is_collection": False,
        "nodata_means_zero": True,
        "comparison": "gt",
        "thresholds": [
            {"type": "absolute", "value": 0.001, "label": "abs"},
        ],
    },
    {
        "asset_id": "projects/unicef-ccri/assets/hazards/LS_RF_Mean_1980-2018_COG",
        "name": "LS_RF_GFDRR_1980-2018",
        "is_collection": False,
        "nodata_means_zero": False,
        "comparison": "gt",
        "thresholds": [
            {"type": "absolute", "value": 0.01, "label": "abs"},
        ],
    },
    {
        "asset_id": "projects/unicef-ccri/assets/hazards/earthquake_v2023_1_pga_475_rock_3min",
        "name": "EQ_475yr_GEM_2023",
        "is_collection": False,
        "nodata_means_zero": False,
        "comparison": "gt",
        "thresholds": [
            {"type": "absolute", "value": 0.09, "label": "abs"},
        ],
    },
    {
        "asset_id": "projects/unicef-ccri/assets/hazards/hol_volcanoes_1800_100kmbuff",
        "name": "GVP_Hol_volcanoes_1800",
        "is_collection": False,
        "nodata_means_zero": False,
        "comparison": "lt",
        "thresholds": [
            {"type": "absolute", "value": 100, "label": "abs"},
        ],
    },
]

# =========================================================================
# 3. HELPER FUNCTIONS
# =========================================================================

def load_hazard_image(cfg):
    """Load hazard layer and apply optional pre-masking."""
    if cfg["is_collection"]:
        img = ee.ImageCollection(cfg["asset_id"]).mosaic()
    else:
        img = ee.Image(cfg["asset_id"])

    # Select first band only — avoids band-count mismatches in multiply/cat
    img = img.select(0)

    if "pre_mask_lte" in cfg:
        img = img.updateMask(img.lte(cfg["pre_mask_lte"]))

    return img

def compute_mean_threshold(layer, geometry):
    """Compute scalar mean of a hazard layer over a geometry (server-side → client)."""
    result = layer.reduceRegion(
        reducer=ee.Reducer.mean(),
        geometry=geometry,
        scale=target_scale,
        bestEffort=True,
        maxPixels=1e13,
    )
    val = result.values().get(0)
    return ee.Number(val).getInfo()

def build_stack(cfg, hazard_img, pop, thresholds_resolved):
    """
    Build a multi-band ee.Image whose per-band sums (via reduceRegions) give
    all the component quantities we need.

    Bands produced
    ──────────────
    hp          H × P  (auto-masked: only where both have data)
                → numerator for weighted average (both strategies share this)
    p_both      P masked to where H has data
                → denominator for Strategy B (intersection weights)
    p_total     P (unmodified)
                → denominator for Strategy A (total-pop weights) + total pop
    exp_<label> P masked to where H passes threshold (one per threshold)
                → exposed population per threshold variant

    Numerator is shared by weighted strategies (only denominator differs).
    """
    bands = []

    # ── Weighted-average components ──
    bands.append(hazard_img.multiply(pop).rename("hp"))
    bands.append(pop.updateMask(hazard_img.mask()).rename("p_both"))
    bands.append(pop.rename("p_total"))

    # ── Exposed-population bands (one per threshold variant) ──
    for th_def, th_val in zip(cfg["thresholds"], thresholds_resolved):
        th_img = ee.Image.constant(th_val)
        if cfg["comparison"] == "gt":
            mask = hazard_img.gt(th_img)
        else:
            mask = hazard_img.lt(th_img)
        bands.append(pop.updateMask(mask).rename(f"exp_{th_def['label']}"))

    return ee.Image.cat(bands)

# =========================================================================
# 4. PRE-COMPUTATION — resolve mean thresholds
# =========================================================================
print("── Resolving mean thresholds ──")

for cfg in hazard_layers:
    H = load_hazard_image(cfg)
    cfg["_thresholds_resolved"] = []
    cfg["_skip"] = False

    for th_def in cfg["thresholds"]:
        if th_def["type"] == "absolute":
            cfg["_thresholds_resolved"].append(th_def["value"])

        elif th_def["type"] == "global_mean":
            val = compute_mean_threshold(H, global_geom)
            if val is None:
                print(f"  ⚠️  {cfg['name']}: could not compute global mean — skipping layer")
                cfg["_skip"] = True
                break
            cfg["_thresholds_resolved"].append(val)
            print(f"  {cfg['name']} global mean  = {val:.6f}")

        elif th_def["type"] == "country_mean":
            val = compute_mean_threshold(H, country_geom)
            if val is None:
                print(f"  ⚠️  {cfg['name']}: could not compute country mean — skipping layer")
                cfg["_skip"] = True
                break
            cfg["_thresholds_resolved"].append(val)
            print(f"  {cfg['name']} country mean = {val:.6f}")

# =========================================================================
# 5a. RUN LOG — write metadata JSON before submitting exports
# =========================================================================
# The log is written here (after thresholds are resolved, before exports)
# so that it captures the exact state of the computation as submitted to GEE.

n_features = admin_fc.size().getInfo()

run_log = {
    "run_timestamp": datetime.now(timezone.utc).isoformat(),
    "run_id": suffix,
    "output_folder": output_folder,

    "admin_boundaries": {
        "asset_id": admin_asset_id,
        "gee_id_field": gee_id_field,
        "output_id_field": id_name,
        "id_field_renamed": gee_id_field != id_name,
        "n_features": n_features,
    },

    "population": {
        "asset_id": pop_asset_id,
        "type": org_totalpop.getInfo()["type"],
        "nominal_scale_m": round(pop_scale.getInfo(), 2),
        "note": (
            "Constrained population raster; nodata interpreted as zero population."
            if "_cn_" in pop_asset_id.lower() else ""
        ),
    },

    "ref_global_boundaries": {
        "asset_id": global_geo_id,
        "note": "Used for global-mean threshold computation.",
    },

    "hazards": [],
}

for cfg in hazard_layers:
    entry = {
        "asset_id": cfg["asset_id"],
        "name": cfg["name"],
        "is_collection": cfg["is_collection"],
        "nodata_means_zero": f"{cfg['nodata_means_zero']} - As of Climate Team Catalogue",
        "comparison": cfg["comparison"],
        "skipped": cfg.get("_skip", False),
    }

    if "pre_mask_lte" in cfg:
        entry["pre_mask_lte"] = cfg["pre_mask_lte"]

    entry["thresholds"] = []
    for th_def, th_val in zip(cfg["thresholds"], cfg.get("_thresholds_resolved", [])):
        th_entry = {
            "label": th_def["label"],
            "type": th_def["type"],
            "resolved_value": th_val,
        }
        # For absolute thresholds the resolved value equals the input;
        # for mean thresholds the resolved value is the computed mean.
        if th_def["type"] == "absolute":
            th_entry["note"] = "User-defined absolute threshold as of Climate Team Catalogue."
        elif th_def["type"] == "global_mean":
            th_entry["note"] = "Mean of hazard layer computed over global geometry."
        elif th_def["type"] == "country_mean":
            th_entry["note"] = "Mean of hazard layer computed over country geometry."
        entry["thresholds"].append(th_entry)

    # entry["weighted_average"] = {
    #     "recommended_strategy": "total_pop" if cfg["nodata_means_zero"] else "intersection",
    #     "rationale": (
    #         "nodata in this layer represents zero hazard intensity; "
    #         "total-population denominator is physically correct."
    #         if cfg["nodata_means_zero"]
    #         else "nodata in this layer represents missing data; "
    #         "intersection denominator avoids artificial dilution."
    #     ),
    # }

    run_log["hazards"].append(entry)

# ── Write log (log_dir same as hazard_folder) ──
log_dir = os.path.join("/content/drive/MyDrive", output_folder)
os.makedirs(log_dir, exist_ok=True)
log_path = os.path.join(log_dir, f"run_log_{suffix}.json")
with open(log_path, "w") as f:
    json.dump(run_log, f, indent=4)
print(f"\n✅  Run log saved: {log_path}")

# =========================================================================
# 5b. MAIN COMPUTATION — reduceRegions per hazard layer
# =========================================================================
print("\n── Submitting export tasks ──")

tasks = []

for cfg in hazard_layers:
    if cfg.get("_skip"):
        continue

    name = cfg["name"]
    print(f"  {name}")

    H = load_hazard_image(cfg)
    stack = build_stack(cfg, H, totalpop, cfg["_thresholds_resolved"])

    # reduceRegions: one server-side call covers ALL admin features
    result_fc = stack.reduceRegions(
        collection=admin_fc,
        reducer=ee.Reducer.sum(),
        scale=pop_scale,
        crs="EPSG:4326",
    )

    # ── Build the list of output columns ──
    # Properties inherited from admin_fc (gee_id_field, e.g. ADM1_CODE) are
    # automatically carried through by reduceRegions.
    band_names = ["hp", "p_both", "p_total"]
    for th_def in cfg["thresholds"]:
        band_names.append(f"exp_{th_def['label']}")

    selectors = [gee_id_field] + band_names

    task = ee.batch.Export.table.toDrive(
        collection=result_fc,
        description=f"{name}_{suffix}",
        folder=output_folder,
        fileFormat="CSV",
        selectors=selectors,
    )
    task.start()
    tasks.append({"name": name, "task": task, "cfg": cfg})

print(f"\n✅  {len(tasks)} export tasks submitted.")

# =========================================================================
# 6. WAIT FOR COMPLETION
# =========================================================================
# (Run this cell separately if you prefer to check back later.)

n_total = len(tasks)
while True:
    statuses = {t["name"]: t["task"].status()["state"] for t in tasks}
    n_done = sum(1 for s in statuses.values() if s in ("COMPLETED", "FAILED"))
    n_fail = sum(1 for s in statuses.values() if s == "FAILED")
    print(f"  {n_done}/{n_total} done ({n_fail} failed)")
    if n_done == n_total:
        break
    time.sleep(30)

failed = [t["name"] for t in tasks if t["task"].status()["state"] == "FAILED"]
if failed:
    print(f"⚠️  Failed tasks: {failed}")
else:
    print("✅  All tasks completed successfully.")

# =========================================================================
# 7. POST-PROCESSING — compute derived metrics in pandas
# =========================================================================
# This is where the final weighted averages and coverage metrics are
# calculated from the component sums exported by GEE.

hazard_folder = os.path.join("/content/drive/MyDrive", output_folder)
output_dir = "/content/drive/MyDrive/exposure_wavg"
os.makedirs(output_dir, exist_ok=True)

# Build a lookup from hazard name → config
cfg_lookup = {cfg["name"]: cfg for cfg in hazard_layers if not cfg.get("_skip")}

all_frames = []

for csv_path in sorted(glob.glob(f"{hazard_folder}/*.csv")):
    df = pd.read_csv(csv_path).rename(
        columns={gee_id_field: id_name}
    )

    # Identify which hazard this file belongs to, from the filename
    basename = os.path.basename(csv_path).replace(f"_{suffix}.csv", "")
    if basename not in cfg_lookup:
        print(f"  ⚠️  Skipping unrecognised file: {csv_path}")
        continue

    cfg = cfg_lookup[basename]

    # ── Derived columns ──

    # Population-weighted average — Strategy A (total-population denominator)
    # Appropriate when nodata = zero hazard intensity
    df["wavg_total_pop"] = df["hp"] / df["p_total"]

    # Population-weighted average — Strategy B (intersection denominator)
    # Appropriate when nodata = missing data
    df["wavg_intersection"] = df["hp"] / df["p_both"]

    # Recommended weighted average (based on the nodata_means_zero flag)
    if cfg["nodata_means_zero"]:
        df["wavg_recommended"] = df["wavg_total_pop"]
        df["wavg_strategy"] = "total_pop"
    else:
        df["wavg_recommended"] = df["wavg_intersection"]
        df["wavg_strategy"] = "intersection"

    # Data coverage — what fraction of the admin's population lives where
    # the hazard layer has actual data
    df["pop_data_coverage"] = df["p_both"] / df["p_total"]

    # Total population (rename for clarity)
    df["total_population"] = df["p_total"]

    # Rename exposed-pop columns to be self-documenting
    for th_def, th_val in zip(cfg["thresholds"], cfg["_thresholds_resolved"]):
        src_col = f"exp_{th_def['label']}"
        dst_col = f"pop_exposed_{th_def['label']}"
        if src_col in df.columns:
            df.rename(columns={src_col: dst_col}, inplace=True)
            # Store the actual threshold value used
            df[f"threshold_{th_def['label']}"] = th_val
            df[f"threshold_{th_def['label']}_type"] = th_def["type"]

    # Hazard metadata
    df["hazard_name"] = cfg["name"]
    df["nodata_means_zero"] = cfg["nodata_means_zero"]
    df["comparison"] = cfg["comparison"]

    # ── Handle division edge cases (0 pop → NaN is correct) ──
    # NaN weighted average when no population → leave as-is (means no people)

    all_frames.append(df)

    # ── Save per-hazard CSV ──
    out_path = os.path.join(output_dir, f"{cfg['name']}_exposure_wavg_{suffix}.csv")
    df.to_csv(out_path, index=False)
    print(f"  ✅  {out_path}")

# ── Save combined CSV (wide format) ──
if all_frames:
    combined = pd.concat(all_frames, ignore_index=True)
    combined_path = os.path.join(output_dir, f"all_hazards_exposure_wavg_{suffix}.csv")
    combined.to_csv(combined_path, index=False)
    print(f"\n✅  Combined output: {combined_path}")
    print(f"    {len(combined)} rows × {len(combined.columns)} columns")
    print(f"    Hazards: {combined['hazard_name'].nunique()}")
    print(f"    Admin areas: {combined[id_name].nunique()}")